source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '9.0'

target 'NJHNavigationBarSelectorPageViewController_Example' do
  pod "NJHNavigationBarSelectorPageViewController", :path => "../"
end
